spring:
  application:
    name: auth-service
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: auth
    open-in-view: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8080
management:
  endpoints:
    web:
      exposure:
        include: health,info
jwt:
  secret: ${JWT_SECRET:default-super-secret-key-for-dev-only}
  exp-min: 60